### ISSUE TITLE
hey there! some concerns

### ISSUE THREAD

**Issue by yuhao-nyc** [swehacker/jquery.gauge#1]
awesome plugin, was play around with it. so I got few questions.
1. if it is possible to start the indicator in the middle of the circle? like leave the half part of the circle empty?
2. remove the "%" totally? put my own divs or spans over the gauge?

Thank you very much

**Comment by swehacker** [comment]
Thank you for your feedback!
1. I actually removed the initial value in the latest release, because of problems using the gauge in different modes (as a jquery plugin or just as a javascript plugin). I can fix this in the next release.
2. You can easily change the % or change it to something else by adding the option $("#myGauge").gauge(70, { unit: "" }) or writing $("#myGauge").gauge(70, { unit: "Volts" })

If you want more control you can create the gauge in different way like this (example for half circle mode):

```
var gaugeCanvas = document.getElementById("gauge8");
var gauge = new HalfCircleGauge(gaugeCanvas, {color: "#FFF", colorAlpha: 0.7});
gauge.value(0);
var randomValue = function() {
    gauge.value(Math.round(Math.random() * 100));
}
setInterval(randomValue, 1000);
```

I will update the documentation with some more examples.

Please let me know if you have more questions!
Patrik

**Comment by yuhao-nyc** [comment]
thanks for the quick reply, I think i didnt explained my issue clear. I will post an image
![image](https://cloud.githubusercontent.com/assets/4121735/6190252/861b50f6-b36e-11e4-8fad-e70663692844.png)

**Comment by yuhao-nyc** [comment]
so the left/right half part of the circles have no color at all, only the other half part changes, to indicate.

**Comment by yuhao-nyc** [comment]
![image](https://cloud.githubusercontent.com/assets/4121735/6190291/ca934590-b36e-11e4-98aa-6dbe4cd4909c.png)
 this is what i did so far, from the plugin

**Comment by swehacker** [comment]
I am not sure I understand, maybe it will be easier if I knew how or what you would use it for?

**Comment by yuhao-nyc** [comment]
another question, is it possible to customize the width of the 2 circles (somehow make it same amount of stroke width) i played around with this part 
ctx.beginPath();
    ctx.strokeStyle = settings.bgcolor;
    ctx.lineWidth = W \* 0.08; //changed from 0.13--0.08
    ctx.arc(centerW, H - (centerW - ctx.lineWidth), (centerW) - ctx.lineWidth, radians(135), radians(45), false);
    ctx.stroke();

**Comment by yuhao-nyc** [comment]
so for the mock up i had in here 
![image](https://cloud.githubusercontent.com/assets/4121735/6192262/1a418110-b37e-11e4-9789-83312c407a3d.png)
its the same gauge ur lovely plugin worked, only i was trying to achieve is starting from the middle point (50%). not from the original (0%--100%). and the blue/red color will work Left/Right growing, from the middle (as 0% to 100%) like a deviation left/right.
i feel its something some much complicate and was searching around, no similar answers.

**Comment by yuhao-nyc** [comment]
like a different angle to start, if thats the word to put in here.

**Comment by swehacker** [comment]
### Line width

ctx.lineWidth = W \* 0.08 is the line width of the arc. It's the width of the canvas \* 0.08. I use it for calculate the widths and heights depending on the size of the canvas. Smaller canvas, thinner lines and the other way around.

### Regarding your gauge design

It requires a new type of gauge, all the components is there but needs to break out to a new gauge type (like the other two) which can handle a value and deviation. Current gauges just handles a singe value, by design.

**Comment by yuhao-nyc** [comment]
pretty clear. thanks Patrik! really appreciate your help!
